### ISSUE TITLE
Regra número de linhas endereço cliente

### ISSUE THREAD

**Issue by danilogubee** [maco-studios/gubee-integration#3]
Ao executar o comando CreatedCommand para criação do pedido no Magento, foi retornado que o endereço está inválido.
Conferido que o endereço estava completo no pedido:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/d4144ec0-40d1-44b7-9224-25b0d0f060f9)

![image](https://github.com/maco-studios/gubee-integration/assets/165683575/1213d7d6-47f1-4a46-845b-89eb28b08ed7)

Trace:
"trace": "#0 /var/www/html/cowboystoreloja/vendor/pagarme/pagarme-magento2-module/Observer/CustomerAddressSaveBefore.php(28): Pagarme\\Pagarme\\Observer\\CustomerAddressSaveBefore->addressValidation()\n#1 /var/www/html/cowboystoreloja/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Pagarme\\Pagarme\\Observer\\CustomerAddressSaveBefore->execute()\n#2 /var/www/html/cowboystoreloja/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod()\n#3 /var/www/html/cowboystoreloja/vendor/magento/framework/Event/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch()\n#4 /var/www/html/cowboystoreloja/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch()\n#5 /var/www/html/cowboystoreloja/vendor/magento/framework/Model/AbstractModel.php(702): Magento\\Framework\\Event\\Manager\\Proxy->dispatch()\n#6 /var/www/html/cowboystoreloja/vendor/magento/module-customer/Model/Address/AbstractAddress.php(525): Magento\\Framework\\Model\\AbstractModel->beforeSave()\n#7 /var/www/html/cowboystoreloja/vendor/magento/module-eav/Model/Entity/VersionControl/AbstractEntity.php(73): Magento\\Customer\\Model\\Address\\AbstractAddress->beforeSave()\n#8 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Eav\\Model\\Entity\\VersionControl\\AbstractEntity->save()\n#9 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Customer\\Model\\ResourceModel\\Address\\Interceptor->___callParent()\n#10 /var/www/html/cowboystoreloja/vendor/magento/framework/App/Cache/FlushCacheByTags.php(69): Magento\\Customer\\Model\\ResourceModel\\Address\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#11 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(135): Magento\\Framework\\App\\Cache\\FlushCacheByTags->aroundSave()\n#12 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Customer\\Model\\ResourceModel\\Address\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#13 /var/www/html/cowboystoreloja/generated/code/Magento/Customer/Model/ResourceModel/Address/Interceptor.php(32): Magento\\Customer\\Model\\ResourceModel\\Address\\Interceptor->___callPlugins()\n#14 /var/www/html/cowboystoreloja/vendor/magento/framework/Model/AbstractModel.php(655): Magento\\Customer\\Model\\ResourceModel\\Address\\Interceptor->save()\n#15 /var/www/html/cowboystoreloja/vendor/magento/module-customer/Model/ResourceModel/AddressRepository.php(139): Magento\\Framework\\Model\\AbstractModel->save()\n#16 /var/www/html/cowboystoreloja/vendor/magento/module-quote/Model/QuoteManagement.php(658): Magento\\Customer\\Model\\ResourceModel\\AddressRepository->save()\n#17 /var/www/html/cowboystoreloja/vendor/magento/module-quote/Model/QuoteManagement.php(501): Magento\\Quote\\Model\\QuoteManagement->_prepareCustomerQuote()\n#18 /var/www/html/cowboystoreloja/vendor/magento/module-quote/Model/QuoteManagement.php(453): Magento\\Quote\\Model\\QuoteManagement->submitQuote()\n#19 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Quote\\Model\\QuoteManagement->submit()\n#20 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callParent()\n#21 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#22 /var/www/html/cowboystoreloja/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(32): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callPlugins()\n#23 /var/www/html/cowboystoreloja/vendor/magento/module-quote/Model/QuoteManagement.php(411): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->submit()\n#24 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Quote\\Model\\QuoteManagement->placeOrder()\n#25 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callParent()\n#26 /var/www/html/cowboystoreloja/vendor/bistwobis/customer-bistwobis/Plugin/Quote/QuoteManagement.php(52): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#27 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(135): Bistwobis\\CustomerBistwobis\\Plugin\\Quote\\QuoteManagement->aroundPlaceOrder()\n#28 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#29 /var/www/html/cowboystoreloja/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callPlugins()\n#30 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Command/Sales/Order/Processor/CreatedCommand.php(298): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->placeOrder()\n#31 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Command/Sales/Order/Processor/CreatedCommand.php(151): Gubee\\Integration\\Command\\Sales\\Order\\Processor\\CreatedCommand->persistOrder()\n#32 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Command/Sales/Order/Processor/CreatedCommand.php(130): Gubee\\Integration\\Command\\Sales\\Order\\Processor\\CreatedCommand->create()\n#33 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Command/AbstractCommand.php(138): Gubee\\Integration\\Command\\Sales\\Order\\Processor\\CreatedCommand->doExecute()\n#34 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Command/Sales/Order/AbstractProcessorCommand.php(96): Gubee\\Integration\\Command\\AbstractCommand->execute()\n#35 /var/www/html/cowboystoreloja/vendor/symfony/console/Command/Command.php(255): Gubee\\Integration\\Command\\Sales\\Order\\AbstractProcessorCommand->execute()\n#36 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Command/AbstractCommand.php(73): Symfony\\Component\\Console\\Command\\Command->run()\n#37 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Model/Message/Management.php(220): Gubee\\Integration\\Command\\AbstractCommand->run()\n#38 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Model/Message/Management.php(136): Gubee\\Integration\\Model\\Message\\Management->execute()\n#39 /var/www/html/cowboystoreloja/vendor/gubee/integration/src/Controller/Adminhtml/Message/Execute.php(41): Gubee\\Integration\\Model\\Message\\Management->process()\n#40 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(58): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute->execute()\n#41 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(138): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->___callParent()\n#42 /var/www/html/cowboystoreloja/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#43 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(135): Magento\\Framework\\App\\Action\\Plugin\\ActionFlagNoDispatchPlugin->aroundExecute()\n#44 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(153): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#45 /var/www/html/cowboystoreloja/generated/code/Gubee/Integration/Controller/Adminhtml/Message/Execute/Interceptor.php(23): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->___callPlugins()\n#46 /var/www/html/cowboystoreloja/vendor/magento/framework/App/Action/Action.php(111): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->execute()\n#47 /var/www/html/cowboystoreloja/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\\Framework\\App\\Action\\Action->dispatch()\n#48 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch()\n#49 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(138): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->___callParent()\n#50 /var/www/html/cowboystoreloja/vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php(76): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#51 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\\Backend\\Plugin\\Utility->aroundDispatch()\n#52 /var/www/html/cowboystoreloja/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#53 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch()\n#54 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(153): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#55 /var/www/html/cowboystoreloja/generated/code/Gubee/Integration/Controller/Adminhtml/Message/Execute/Interceptor.php(32): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->___callPlugins()\n#56 /var/www/html/cowboystoreloja/vendor/magento/framework/App/FrontController.php(186): Gubee\\Integration\\Controller\\Adminhtml\\Message\\Execute\\Interceptor->dispatch()\n#57 /var/www/html/cowboystoreloja/vendor/magento/framework/App/FrontController.php(118): Magento\\Framework\\App\\FrontController->processRequest()\n#58 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch()\n#59 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent()\n#60 /var/www/html/cowboystoreloja/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#61 /var/www/html/cowboystoreloja/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins()\n#62 /var/www/html/cowboystoreloja/vendor/magento/framework/App/Http.php(116): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch()\n#63 /var/www/html/cowboystoreloja/vendor/magento/framework/App/Bootstrap.php(263): Magento\\Framework\\App\\Http->launch()\n#64 /var/www/html/cowboystoreloja/pub/index.php(40): Magento\\Framework\\App\\Bootstrap->run()\n#65 {main}"

**Comment by macoaure** [comment]
Boa tarde @danilogubee,

Apliquei uma correção para adicionar a compatibilidade com o modulo Pagarme.

Atenciosamente.
